spring.application.name=backend
spring.data.mongodb.uri=${SPRING_MONGODB_URI:mongodb+srv://madhav:<db_password>@clustermedi.g2s0aiz.mongodb.net/medconnect?appName=ClusterMedi}
spring.data.mongodb.database=${SPRING_MONGODB_DATABASE:medconnect}
server.port=${PORT:8080}